version: '3'
services:
  postgres:
    build: docker/postgres
    image: postgres
  mongo:
    build: docker/mongo
    image: mongo
  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    image: flask
    volumes:
      - ./source/python:/python
      - ./source/web/static:/python/d4d/static
      - ./source/web/templates:/python/d4d/templates
    ports:
      - 5001:5001
    depends_on:
      - postgres
      - mongo
    env_file: docker.env
  conda:
    build:
      context: .
      dockerfile: ./docker/conda/Dockerfile
    image: conda
    volumes:
      - ./source/python:/python
      - ./source/notebooks:/opt/notebooks
    ports:
      - 5002:5002
    depends_on:
      - postgres
      - mongo
    env_file: docker.env
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: node
    volumes:
      - ./source/node/src/:/node/src
      - ./source/node/package.json:/node/package.json
    ports:
      - 5003:5003
