version: '3'
services:
  postgres:
    build: docker/postgres
    image: postgres
  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    image: flask
    volumes:
      - ./source/python:/python
    ports:
      - 5001:5001
    depends_on:
      - postgres
    env_file: docker.env
  conda:
    build:
      context: .
      dockerfile: ./docker/conda/Dockerfile
    image: conda
    volumes:
      - ./source/python:/python
      - ./source/notebooks:/opt/notebooks
    ports:
      - 5002:5002
    depends_on:
      - postgres
    env_file: docker.env
